### ISSUE TITLE
Update the scrapper for quotes.toscrape.com

### ISSUE THREAD

**Issue by Facundo-Barbera** [Facundo-Barbera/Scraping-Library#11]
# Big update for scrapper

This update will provide the scrapper with new functions that make it quicker. This is to explore the capabilities of scrapping asynchronously and other methods.

## To-do

- [x] Rename QuotesToScrapeScrapper to QuotesToScrape (*It seems redundant to call it scrapper since it's implied in the library name*)
- [x] Add preloaded_scrape function
- [x] Make scrape function async
- [x] Add logging to replace the verbose option
